export const FETCH_REQUESTLESS_REQUEST = 'FETCH_REQUESTLESS_REQUEST';
export const FETCH_REQUESTLESS_SUCCESS = 'FETCH_REQUESTLESS_SUCCESS';
export const FETCH_REQUESTLESS_FAILURE = 'FETCH_REQUESTLESS_FAILURE';
