export const CREATE_NEW_ROAD = 'CREATE_NEW_ROAD';
export const OPEN_CREATE_NEW_ROAD_DIALOG = 'OPEN_CREATE_NEW_ROAD_DIALOG';
export const CLOSE_CREATE_NEW_ROAD_DIALOG = 'CLOSE_CREATE_NEW_ROAD_DIALOG';
