export const SELECT_ROAD = 'SELECT_ROAD';
export const SELECT_BRIDGE = 'SELECT_BRIDGE';
export const SELECT_DANGER_ROAD = 'SELECT_DANGER_ROAD';
export const SELECT_SEGMENT = 'SELECT_SEGMENT';
export const SELECT_CITY = 'SELECT_CITY';
export const SELECT_AIRFIELD = 'SELECT_AIRFIELD';
export const SELECT_AMBULANCE = 'SELECT_AMBULANCE';
